### ISSUE TITLE
kp_box 'not found' error

### ISSUE THREAD

**Issue by andreweatherman** [saiemgilani/kenpomR#40]
Very similar to the scheduling bug that I reported a few days ago:

When running the `kp_box` function for last season, I run into the following error with numerous games:

> Error in kp_box(game_id = game_id, year = 2021) : object 'kenpom' not found

Again, I'm not sure what is causing this error as the url that the function is calling _does_ redirect to a legitimate box score on KenPom. I filtered out games (working with a long list of game IDs for last season) against non-D1 opponents, too, thinking that might solve the issue, but it didn't.

The function calls the following url:

>  url <- paste0("https://kenpom.com/box.php?", "g=", game_id, 
>             "&y=", year)

Running an example game, game_id=6, through the function yields the error mentioned above, `kp_box(game_id=6, year=2021)`, however, the url that the function should be redirecting to _does_ exist: https://kenpom.com/box.php?g=6&y=2021.

The function is working for some games (e.g. `kp_box(game_id=1, year=2021)`), but I cannot figure out why it is returning an error for others. The missing games do not go into OT, nor are their box scores formatted differently. It's not an issue with specific teams, either. I'm not sure how many box scores this affects, but the issue is certainly not isolated.

**Comment by saiemgilani** [comment]
For the record, I was not able to save the referee ranks **and** solve the zero referee case (I chose to solve the zero case), _but_ I did realize I never implemented a pretty easy function `kp_referee()` that allows you to pull the ranks should you desire, as well as the gamelog for a referee.
